# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
error_symbol = "[âœ—](bold red)"
# use_symbol_for_status = true
success_symbol = "[âœ](bold green)"     # The "symbol" segment is being set to "âœ"

[conda]
symbol = "â‚¬ "
style = "fg:red"

[git_branch]
symbol = "ğŸŒ¿ "